app:
  url: https://team-2.proj-sum.it.p.lodz.pl

otp:
  secret: 26Etz0ZMoBmiX7F9lHvb

jws:
  secret: 6f97ca1e5fdf4a418bf0ad0badd33dd716f63e7f593a4b7f9e4b4304316fd09a

oauth2:
  client:
    id: 646977083886-0hbur7doj5r5p6jmcs0k2qd3akhk5cns.apps.googleusercontent.com
    secret: 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
  auth:
    url: https://accounts.google.com/o/oauth2/v2/auth
  token:
    url: https://oauth2.googleapis.com/token
  redirect:
    url: https://team-2.proj-sum.it.p.lodz.pl/auth/google/callback

jwt:
  privateKeyFilePath: /etc/ssbd02/privateJwt-key.pem
  publicKeyFilePath: classpath:keys/publicJwt-key.pem
  expiration: 1

refreshToken:
  privateKeyFilePath: /etc/ssbd02/privateRefresh-key.pem
  publicKeyFilePath: classpath:keys/publicRefresh-key.pem
  expiration: 24

db:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://db:5432/ssbd02
  defaultTransactionIsolation: 2
  admin:
    username: ssbd02admin
    password: adminP@ssw0rd
  auth:
    username: ssbd02auth
    password: authP@ssw0rd
  mok:
    username: ssbd02mok
    password: mokP@ssw0rd
  mol:
    username: ssbd02mol
    password: molP@ssw0rd

login:
  maxAttempts: 3
  timeOut: 86400

mail:
  host: smtp.gmail.com
  port: 587
  username: landlordkingdomssbd02@gmail.com
  password: xbig gjqb fhsu ziqz
  smtp:
    auth: true
    starttls:
      enable: true
  transfer:
    protocol: smtp

scheduler:
  threadPool:
    size: 5

account:
  removeUnverifiedAccountAfterHours: 24
  deactivateAccountAfterDays: 31

transaction:
  timeout: 8