services:
  db:
    image: mysql:9.0.1
    container_name: ssbd02-db
    restart: always
    environment:
      MYSQL_USER: postgres
      MYSQL_ROOT_PASSWORD: postgres
      MYSQL_PASSWORD: postgres
    ports:
      - "3306:3306"
    networks:
      - my_network
    volumes:
      - ./initDb.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]

  tomcat:
    build:
      context: ..
      dockerfile: docker-ssbd02/DockerfileTomcat
    container_name: ssbd02-tomcat
    restart: always
    ports:
      - "8080:8080"
    networks:
      - my_network
    environment:
      - ACTIVE_PROFILE=dev
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./privateJwt-key.pem:/etc/ssbd02/privateJwt-key.pem
      - ./privateRefresh-key.pem:/etc/ssbd02/privateRefresh-key.pem

  nginx:
    image: nginx:1.21.3
    container_name: ssbd02-nginx
    restart: always
    depends_on:
      - tomcat
    ports:
      - "9090:80"
    networks:
      - my_network
    volumes:
      - ./nginxdev.conf:/etc/nginx/nginx.conf

  smtp4dev:
    image: rnwood/smtp4dev
    container_name: smtp4dev
    restart: always
    depends_on:
      - tomcat
    ports:
      - "5000:80"
      - "25:25"
    networks:
      - my_network

networks:
  my_network:
