version: '3.8'

services:
  db:
    image: postgres:16.2
    container_name: ssbd02-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - ./initDb.sql:/docker-entrypoint-initdb.d/init.sql


  tomcat:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: ssbd02-tomcat
    restart: always
    ports:
      - "8080:8080"
    networks:
      - my_network
    depends_on:
      - db
    volumes:
      - ./privateJwt-key.pem:/etc/ssbd02/privateJwt-key.pem
      - ./privateRefresh-key.pem:/etc/ssbd02/privateRefresh-key.pem


  smtp4dev:
    image: rnwood/smtp4dev
    container_name: smtp4dev
    restart: always
    ports:
      - "5000:80"
      - "25:25"
    networks:
      - my_network


networks:
  my_network: