version: '3.8'

services:
  db:
    image: postgres:16.2
    container_name: ssbd02-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - ./initDb.sql:/docker-entrypoint-initdb.d/init.sql

  tomcat:
    build:
      context: ..
      dockerfile: DockerfileTomcat
    container_name: ssbd02-tomcat
    restart: always
    ports:
      - "8080:8080"
    networks:
      - my_network
    depends_on:
      - db
    volumes:
      - /etc/ssbd02/privateJwt-key.pem:/etc/ssbd02/privateJwt-key.pem
      - /etc/ssbd02/privateRefresh-key.pem:/etc/ssbd02/privateRefresh-key.pem

  nginx:
    build:
      context: ..
      dockerfile: DockerfileNginx
    container_name: ssbd02-nginx
    restart: always
    ports:
      - "3000:80"
    networks:
      - my_network
    depends_on:
      - tomcat
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf


networks:
  my_network: