version: '3.8'

services:
  db:
    image: mysql:9.0.1
    container_name: ssbd02-db
    restart: always
    environment:
      MYSQL_USER: postgres
      MYSQL_ROOT_PASSWORD: postgres
      MYSQL_PASSWORD: postgres
    networks:
      - my_network
    volumes:
      - ./initDb.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]

  tomcat:
    build:
      context: ..
      dockerfile: docker-ssbd02/DockerfileTomcat
    container_name: ssbd02-tomcat
    restart: always
    environment:
      - ACTIVE_PROFILE=prod
    networks:
      - my_network
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./privateJwt-key.pem:/etc/ssbd02/privateJwt-key.pem
      - ./privateRefresh-key.pem:/etc/ssbd02/privateRefresh-key.pem

  nginx:
    build:
      context: ..
      dockerfile: docker-ssbd02/DockerfileNginx
    container_name: ssbd02-nginx
    restart: always
    ports:
      - "443:443"
    networks:
      - my_network
    depends_on:
      - tomcat
    volumes:
      - ./tua202402.pl.crt:/etc/cert/tua202402.pl.crt
      - ./tua202402.pl.key:/etc/cert/tua202402.pl.key
      - ./nginx.conf:/etc/nginx/nginx.conf


networks:
  my_network: