version: '3.8'

services:
  db:
    image: postgres:16.2-alpine
    container_name: ssbd02-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - ./initDb.sql:/docker-entrypoint-initdb.d/init.sql

  tomcat:
    build:
      context: ..
      dockerfile: docker-ssbd02/DockerfileTomcat
    container_name: ssbd02-tomcat
    restart: always
    environment:
      - ACTIVE_PROFILE=prod
    ports:
      - "8080:8080"
    networks:
      - my_network
    depends_on:
      - db
    volumes:
      - /etc/ssbd02/privateJwt-key.pem:/etc/ssbd02/privateJwt-key.pem
      - /etc/ssbd02/privateRefresh-key.pem:/etc/ssbd02/privateRefresh-key.pem

  nginx:
    build:
      context: ..
      dockerfile: docker-ssbd02/DockerfileNginx
    container_name: ssbd02-nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - my_network
    depends_on:
      - tomcat
    volumes:
      - /home/student/fullchain.pem:/etc/letsencrypt/live/team-2.proj-sum.it.p.lodz.pl/fullchain.pem
      - /home/student/privkey.pem:/etc/letsencrypt/live/team-2.proj-sum.it.p.lodz.pl/privkey.pem
      - ./nginx.conf:/etc/nginx/nginx.conf


networks:
  my_network: